export const campaignData = [
  {
    commission: "Sales",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_yellow_900_5x3.svg",
    percentage: 21,
  },
  {
    commission: "Commission",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_red_500_01.svg",
    percentage: 11,
  },
  {
    commission: "Brand Referral Bonus",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_5x3.svg",
    percentage: 7,
  },
  {
    commission: "Clicks",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_1.svg",
    percentage: 22,
  },
  {
    commission: "Detail Page Views",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_yellow_900_5x3.svg",
    percentage: 9,
  },
  {
    commission: "Add to Carts",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_2.svg",
    percentage: 16,
  },
  {
    commission: "Conversions",
    amount: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_vector_1.svg",
    percentage: 10,
  },
];

export const hpDateData = [
  {
    sundayText: "Su",
    mondayText: "Mo",
    tuesdayText: "Tu",
    wednesdayText: "We",
    thursdayText: "Th",
    fridayText: "Fr",
    saturdayText: "Sa",
  },
  {
    sundayText: "28",
    mondayText: "29",
    tuesdayText: "30",
    wednesdayText: "1",
    thursdayText: "2",
    fridayText: "3",
    saturdayText: "4",
  },
  {
    sundayText: "5",
    mondayText: "6",
    tuesdayText: "7",
    wednesdayText: "8",
    thursdayText: "9",
    fridayText: "10",
    saturdayText: "11",
  },
  {
    sundayText: "12",
    mondayText: "13",
    tuesdayText: "14",
    wednesdayText: "15",
    thursdayText: "16",
    fridayText: "17",
    saturdayText: "18",
  },
  {
    sundayText: "19",
    mondayText: "20",
    tuesdayText: "21",
    wednesdayText: "22",
    thursdayText: "23",
    fridayText: "24",
    saturdayText: "25",
  },
  {
    sundayText: "26",
    mondayText: "27",
    tuesdayText: "28",
    wednesdayText: "29",
    thursdayText: "30",
    fridayText: "31",
    saturdayText: "1",
  },
];
