export const campaignData = [
  {
    label: "Sales",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_settings_white_a700_1.svg",
    percentage: 21,
    iconBgColor: "#fb7e10",
  },
  {
    label: "Commission",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_contrast.svg",
    percentage: 11,
    iconBgColor: "white",
  },
  {
    label: "Brand Referral Bonus",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_car.svg",
    percentage: 7,
    iconBgColor: "white",
  },
  {
    label: "Clicks",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_contrast_green_200.svg",
    percentage: 22,
    iconBgColor: "white",
  },
  {
    label: "Detail Page Views",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_user_yellow_900.svg",
    percentage: 9,
    iconBgColor: "white",
  },
  {
    label: "Add to Carts",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_cart.svg",
    percentage: 16,
    iconBgColor: "white",
  },
  {
    label: "Conversions",
    value: `$${(Math.random(1000, 10000) * 10000).toFixed(2)}`,
    image: "img_settings_red_500_01.svg",
    percentage: 10,
    iconBgColor: "white",
  },
];

export const hpDateData = [
  {
    sundayText: "Su",
    mondayText: "Mo",
    tuesdayText: "Tu",
    wednesdayText: "We",
    thursdayText: "Th",
    fridayText: "Fr",
    saturdayText: "Sa",
  },
  {
    sundayText: "28",
    mondayText: "29",
    tuesdayText: "30",
    wednesdayText: "1",
    thursdayText: "2",
    fridayText: "3",
    saturdayText: "4",
  },
  {
    sundayText: "5",
    mondayText: "6",
    tuesdayText: "7",
    wednesdayText: "8",
    thursdayText: "9",
    fridayText: "10",
    saturdayText: "11",
  },
  {
    sundayText: "12",
    mondayText: "13",
    tuesdayText: "14",
    wednesdayText: "15",
    thursdayText: "16",
    fridayText: "17",
    saturdayText: "18",
  },
  {
    sundayText: "19",
    mondayText: "20",
    tuesdayText: "21",
    wednesdayText: "22",
    thursdayText: "23",
    fridayText: "24",
    saturdayText: "25",
  },
  {
    sundayText: "26",
    mondayText: "27",
    tuesdayText: "28",
    wednesdayText: "29",
    thursdayText: "30",
    fridayText: "31",
    saturdayText: "1",
  },
];
